name: Run Pytest on Push

on:
  push:
    branches: [ main , dev]

jobs:
  test_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or whatever version you're using

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          python -m venv venv
          echo "helo hey"
          pytest tests
